---
- hosts: all
  tasks:
    - name: Download node_exporter
      become: true
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz

    - name: Extract
      become: true
      shell: |
        DIRECTORY=node_exporter-1.0.1.linux-amd64
        if [ -d $DIRECTORY ] 
        then
            rm -rf node_ex*
        else
            tar -zxvf node_exporter-1.0.1.linux-amd64.tar.gz
        fi
        

    - name: Execute
      become: true
      shell: |
        cd node_exporter-1.0.1.linux-amd64
        ./node_exporter &               
