---
- hosts: all
  tasks:
    - name: Download node_exporter
      become: true
      shell: |
        export DIRECTORY=node_exporter-1.0.1.linux-amd64
        export VERSION="node_exporter-1.0.1.linux-amd64"
        if [ -d $DIRECTORY ] 
        then
          rm -rf node_*
          wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/${VERSION}.tar.gz
        else
          wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/${VERSION}.tar.gz
        fi      
        
    - name: Extract
      become: true
      shell: |
        tar -zxvf ${VERSION}.tar.gz

    - name: Execute
      become: true
      shell: |
        cd ${VERSION}
        ./node_exporter &               
