---
- hosts: kube_master
  tasks:
    - name: Create opt directory for prometheus
      file:
        path: /opt/docker/prometheus
        state: directory

    - name: Copy the prometheus.yml
      become: true
      copy:
        src: /tmp/prometheus/prometheus.yml
        dest: /opt/docker/prometheus/prometheus.yml   

    - name: Spin up the Docker Prometheus container
      become: true
      shell: |
        docker stop prometheus
        sleep 2
        docker rm prometheus
        sleep 5
        docker run -it -d --name prometheus -p 9090:9090 -v /opt/docker/prometheus:/etc/prometheus prom/prometheus --config.file=/etc/prometheus/prometheus.yml
