---
- hosts: all
  tasks:
    - name: Download node_exporter
      become: true
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz

    - name: Extract
      become: true
      shell: |
        tar -zxvf node_exporter-1.0.1.linux-amd64.tar.gz && cd node_exporter-1.0.1.linux-amd64.tar.gz

    - name: Execute
      become: true
      shell: |
        ./node_exporter &               
