---
- hosts: kube_master
  tasks:

    # - name: Remove previous docker versions if exists
    #   become: true
    #   shell: |
    #     apt-get remove docker docker-engine docker.io containerd runc -y

    # - name: Install essential Docker packages
    #   become: true
    #   shell: |
    #     apt-mark hold google-cloud-sdk && sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y 

    # - name: Add Dockerfile's official GPG key
    #   become: true
    #   shell: |
    #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -  

    # - name: Add Docker package to apt repository
    #   become: true
    #   shell: |
    #     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 

    # - name: Update the repository
    #   become: true
    #   shell: |
    #     apt-mark hold google-cloud-sdk && apt-get update -y 

    # - name: Install the Docker
    #   become: true
    #   shell: |
    #     apt-get install docker-ce docker-ce-cli containerd.io -y

    # - name: Restasrt and Enable docker 
    #   become: true
    #   shell: |
    #     systemctl restart docker && systemctl enable docker 


    - name: Create /opt/docker/prommetheus
      become: true
      shell: |
        mkdir -p /opt/docker/prometheus && touch /opt/docker/prometheus/prometheus.yml
    
    - name: Spin up the Docker Prometheus container
      become: true
      shell: |
        docker stop prometheus && docker rm prometheus && docker run -it -d --name prometheus -p 9090:9090 -v /opt/docker/prometheus:/etc/prometheus prom/prometheus --config.file=/etc/prometheus/prometheus.yml
