---
- hosts: kube_master
  tasks:

    - name: Install docker
      become: true
      shell: |
        apt-get remove docker docker-engine docker.io && apt install docker.io && systemctl start docker && systemctl enable docker

    - name: Create /opt/docker/prommetheus
      become: true
      shell: |
        mkdir -p /opt/docker/prometheus && touch /opt/docker/prometheus/prometheus.yml
    
    - name: Spin up the Docker Prometheus container
      become: true
      shell: |
        docker run -it -d --name prometheus -p 9090:9090 -v /opt/docker/prometheus:/etc/prometheus prom/prometheus --config.file=/etc/prometheus/prometheus.yml
