---
- hosts: kube-master
  tasks:
    - name: Docker install Grafana
      become: true
      shell: |
        docker run 

    - name: Start the cluster with the current user
      become: ubuntu
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Set the calico network
      become: ubuntu
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
