---
- hosts: kube_master
  tasks:

    - name: Install docker
      become: true
      shell: |
        apt install apt-transport-https ca-certificates curl software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && apt update && apt-cache policy docker-ce && apt install docker-ce && systemctl enable docker && systemctl status docker        

    - name: Create /opt/docker/prommetheus
      become: true
      shell: |
        mkdir -p /opt/docker/prometheus && touch /opt/docker/prometheus/prometheus.yml
    
    - name: Spin up the Docker Prometheus container
      become: true
      shell: |
        docker run -it -d --name prometheus -p 9090:9090 -v /opt/docker/prometheus:/etc/prometheus prom/prometheus --config.file=/etc/prometheus/prometheus.yml
